#!/bin/bash

. common.sh
BASENAME=`basename $0`
QUIET=
#
#
# Update Subscription
#

function usage {
    echo Usage : $BASENAME 'name role display-name [ -h host [ -p user:password ] [ options ]';
    exit 1;
}

[ $# -lt 3 ] && { usage; }

NAME=$1; shift;
ROLE=$1; shift;
DISPLAY_NAME=$1; shift;

[ "$USERPASSWORD" != "" ] && { USERPASSWORD='-u '$USERPASSWORD; }
[ "$HOST" == "" ] && {
        export HOST=http://localhost:2178;
}

curl $QUIET $USERPASSWORD -k -H "Content-Type: application/json" -X POST -d '{
    "name" : "'$NAME'",
    "role" : "'$ROLE'",
    "display_name" : "'$DISPLAY_NAME'"
}' $HOST/backend/admin/profile/resource

echo

