// Generated by CoffeeScript 1.4.0
  var register;

  register = function(file) {
    var type;
    type = require(file);
    exports[type.name] = type;
    try {
      return require("" + file + "-api");
    } catch (_error) {}
  };

  register('./text');
