#!/bin/bash


CURL_OPTIONS='-sS --post301 --post302 -kL'
CURL_OUTINFO='\r\nHTTP CODE : %{http_code}'
BASENAME=`basename $0`
DIR=`dirname $0`
JQ=$DIR/../bin/jq-linux64
TEMPLATE=$DIR/templates/auth-set-social
TMP=/tmp/auth-set-social$$

trap "rm -f $TMP;" SIGHUP SIGINT SIGTERM EXIT
#set -e

function usage {
	echo Usage : $0 'options [ -h host ]';
	echo '      --profile-name     (MANDATORY)  : organization profile name for auth ( "default" for now )';
	echo '      --client-id        (MANDATORY)  : client-id provided by google';
	echo '      --client-secret    (MANDATORY)  : client-secret provided by google';
	echo '      --callback-url     (MANDATORY)  : callback url registered with google for this app';
	exit 1;
}

[ $# -lt 1 ] && { usage; }

AUTH_TYPE="google"

while [ $# -gt 0 ];
do
	[ "$1" == '--profile-name' ] && { PROFILE_NAME=$2; shift; }
	[ "$1" == '--client-id' ] && { CLIENT_ID=$2; shift; }
	[ "$1" == '--client-secret' ] && { CLIENT_SECRET=$2; shift; }
	[ "$1" == '--callback-url' ] && { CALLBACK_URL=$2; shift; }
	[ "$1" == '-h' ] && { HOST=$2; shift; }

	shift;
done

#
# Check for Mandatories
#
[ "$PROFILE_NAME" == "" ] && usage;
[ "$CLIENT_ID" == "" ] && usage;
[ "$CLIENT_SECRET" == "" ] && usage;
[ "$CALLBACK_URL" == "" ] && usage;

#
# Create the request body
#
cp $TEMPLATE $TMP
sed -i 's@/PROFILE_NAME/@'$PROFILE_NAME'@g' $TMP
sed -i 's@/CLIENT_ID/@'$CLIENT_ID'@g' $TMP
sed -i 's@/CLIENT_SECRET/@'$CLIENT_SECRET'@g' $TMP
sed -i 's@/CALLBACK_URL/@'$CALLBACK_URL'@g' $TMP
sed -i 's@/AUTH_TYPE/@'$AUTH_TYPE'@g' $TMP
cat $TMP | $JQ '.'

[ "$HOST" == "" ] && {
		export HOST=http://localhost:2178;
}

curl $CURL_OPTIONS -w "$CURL_OUTINFO" -H "Content-Type: application/json" -X POST -d @$TMP $HOST/auth/config/sso/add

echo
