#!/bin/bash

CURL_OPTIONS='-sS --post301 --post302 -kL'
CURL_OUTINFO='\r\n[ http-code: %{http_code} ]'
BASENAME=`basename $0`
DIR=`dirname $0`
JQ=$DIR/../bin/jq-linux64
TMP=/tmp/backend-get-config-wiziq-end-pts.$$

trap "rm -f $TMP;" SIGHUP SIGINT SIGTERM EXIT
#set -e

function usage {
	echo Usage : $0 'options';
	echo '      -h      : IP or FQDN of backend server';
	echo '      --help  : show this help';
	exit 1;
}

while [ $# -gt 0 ];
do
	[ "$1" == '--help' ] && { usage; }
	[ "$1" == '-h' ] && { HOST=$2; shift; }

	shift;
done

[ "$HOST" == "" ] && {
		export HOST=http://localhost:2178;
}

curl $CURL_OPTIONS -w "$CURL_OUTINFO" -H "Content-Type: application/json" -X DELETE $HOST/backend/admin/wiziq-end-pts > $TMP
[ "$(grep http-code $TMP | grep 200)" = "" ] && cat $TMP;
[ "$(grep http-code $TMP | grep 200)" != "" ] && { cat $TMP | grep -v http-code | $JQ '.'; cat $TMP | grep http-code; }


echo
