#!/bin/bash

CURL_OPTIONS='-sS --post301 --post302 -kL'
CURL_OUTINFO='\r\nHTTP CODE : %{http_code}'
BASENAME=`basename $0`
DIR=`dirname $0`
JQ=$DIR/../bin/jq-linux64
TEMPLATE=$DIR/templates/backend-add-attendee
TMP=/tmp/backend-add-attendee$$

trap "rm -f $TMP;" SIGHUP SIGINT SIGTERM EXIT
#set -e

function usage {
	echo Usage : $0 'options [ -h host ]';
	echo '  options can be a sequence of the following:';
	echo '      --class-id    (MANDATORY) : id of the class to which this attendee should be added';
	echo '      --user-id     (MANDATORY) : unique id of attendee';
	echo '      --email                   : email id';
	echo '      --auth                    : authentication type ("wiziq" | "google" | "facebook")';
	echo '      --display                 : display name';
	echo '      -h                        : ip or FQDN of the backend server';
	exit 1;
}

[ $# -lt 1 ] && { usage; }

ROLE="attendee"

while [ $# -gt 0 ];
do
	[ "$1" == '--class-id' ] && { CLASS_ID=$2; shift; }
	[ "$1" == '--user-id' ] && { USER_ID=$2; shift; }
	[ "$1" == '--email' ] && { EMAIL=$2; shift; }
	[ "$1" == '--auth' ] && { AUTH_VIA=$2; shift; }
	[ "$1" == '--display' ] && { DISPLAY=$2; shift; }
	[ "$1" == '-h' ] && { HOST=$2; shift; }

	shift;
done

#
# Check for Mandatories
#
[ "$CLASS_ID" == "" ] && usage;
[ "$USER_ID" == "" ] && usage;

#
# Create the request body
#
cp $TEMPLATE $TMP
sed -i 's@/CLASS_ID/@'$CLASS_ID'@g' $TMP
sed -i 's@/USER_ID/@'$USER_ID'@g' $TMP
sed -i 's@/EMAIL/@'$EMAIL'@g' $TMP
sed -i 's@/ROLE/@'$ROLE'@g' $TMP
sed -i 's@/AUTH_VIA/@'$AUTH_VIA'@g' $TMP
sed -i 's@/DISPLAY/@'$DISPLAY'@g' $TMP
cat $TMP | $JQ '.'

[ "$HOST" == "" ] && {
		export HOST=http://localhost:2178;
}

curl $CURL_OPTIONS -w "$CURL_OUTINFO" -H "Content-Type: application/json" -X POST -d @$TMP $HOST/backend/wiziq/$CLASS_ID/user

echo
